name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: (TEMP) Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/unblockable/unblocked.git
        working-directory: ../..

      - name: (TEMP) Install unblocked
        run: yarn build:all
        working-directory: ../../unblocked

      - name: Install Dependencies
        run: yarn install --immutable --network-timeout 1000000
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1

      - name: Run "build" step
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn tsc
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1

      - name: Run  Lint
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: 'Tar files'
        run: tar -cvf js_files.tar --exclude=node_modules --exclude=dist ./build

      - name: Upload built Javascript files
        uses: actions/upload-artifact@v2
        with:
          name: js-build
          path: js_files.tar
          retention-days: 1

  test:
    name: Test ${{matrix.browser || 'chrome-98-0' }} (node ${{ matrix.node-version }}; ${{ matrix.os }})
    needs: lint
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]
        include:
          - node-version: 16.x
            os: ubuntu-latest
            browser: chrome-97-0

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: (TEMP) Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/unblockable/unblocked.git
        working-directory: ../..

      - name: (TEMP) Install unblocked
        run: yarn build:all
        working-directory: ../../unblocked
        env:
          SA_REBUILD_MITM_SOCKET: 1

      - name: Download built typescript files
        uses: actions/download-artifact@v2
        with:
          name: js-build
          path: .

      - name: Untar files
        run: tar -xf js_files.tar

      - name: Build modules
        run: yarn --network-timeout 1000000 --verbose
        working-directory: ./build

      - name: Linux - Add Chrome Env
        if: ${{ matrix.browser }}
        working-directory: ../../unblocked/build
        run: yarn add -W @ulixee/${{ matrix.browser }}

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ../../unblocked/build
        run: sudo $(npx install-browser-deps)

      - name: Run tests
        run: yarn jest --testTimeout=60000 --maxWorkers=2
        working-directory: ./build
        env:
          NODE_ENV: test
          HERO_DATA_DIR: .data
          HERO_DEFAULT_BROWSER_ID: ${{ matrix.browser }}

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar ./build/.data

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
