name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  test:
    name: Test ${{matrix.browser || 'chrome-latest' }} (node ${{ matrix.node-version }}; ${{ matrix.os }})
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]
        include:
          - node-version: 16.x
            os: ubuntu-latest
            browser: chrome-97-0

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Clone ulixee/shared
        run: git clone https://github.com/ulixee/shared.git
        working-directory: ../..

      - name: Install ulixee/shared
        run: yarn build
        working-directory: ../../shared

      - name: Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/unblocked-web/unblocked.git
        working-directory: ../..

      - name: Install unblocked
        run: yarn build:all
        working-directory: ../../unblocked
        env:
          UBK_MITM_MITM_SOCKET: 1

      - name: Relink shared
        run: yarn
        working-directory: ../../shared/build

      - name: Build modules
        run: yarn build --network-timeout 1000000

      - name: Run  Lint
        if: ${{ matrix.os == 'ubuntu-latest' && !matrix.browser }}
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: Linux - Add Chrome Env
        if: ${{ matrix.browser }}
        working-directory: ../../unblocked/build
        run: yarn add -W @ulixee/${{ matrix.browser }}

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ../../unblocked/build
        run: sudo $(npx install-browser-deps)

      - name: Run tests
        run: yarn jest --testTimeout=60000 --maxWorkers=2
        working-directory: ./build
        env:
          NODE_ENV: test
          ULX_DATA_DIR: .data
          UBK_DEFAULT_BROWSER_ID: ${{ matrix.browser }}

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar ./build/.data

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
